spring.application.name=users

# Configuración para PostgreSQL (Contenedor local: 5432)
spring.datasource.url=jdbc:postgresql://localhost:5432/sicaeUsuario
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate (Muestra el SQL para depurar)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
