--
-- PostgreSQL database dump
--

\restrict qcGGIkFOhKOT8CaaraSLecakt8ifHnzUyxhhgoRts8h9rlENTEJkRyxFMtZBepb

-- Dumped from database version 17.10
-- Dumped by pg_dump version 17.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: programa_educativo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.programa_educativo (
    id_programa smallint NOT NULL,
    nombre character varying(100) NOT NULL,
    estatus boolean NOT NULL
);


ALTER TABLE public.programa_educativo OWNER TO postgres;

--
-- Name: programa_educativo_id_programa_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.programa_educativo ALTER COLUMN id_programa ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.programa_educativo_id_programa_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rol; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rol (
    id_rol smallint NOT NULL,
    nombre character varying(50) NOT NULL,
    estatus boolean NOT NULL
);


ALTER TABLE public.rol OWNER TO postgres;

--
-- Name: rol_id_rol_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rol ALTER COLUMN id_rol ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rol_id_rol_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipo_usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipo_usuario (
    id_tipo smallint NOT NULL,
    nombre character varying(50) NOT NULL,
    estatus boolean NOT NULL
);


ALTER TABLE public.tipo_usuario OWNER TO postgres;

--
-- Name: tipo_usuario_id_tipo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tipo_usuario ALTER COLUMN id_tipo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipo_usuario_id_tipo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    id_usuario integer NOT NULL,
    nombre character varying(50) NOT NULL,
    apellido_paterno character varying(50) NOT NULL,
    apellido_materno character varying(50),
    clave_usuario character varying(10) NOT NULL,
    email character varying(255) NOT NULL,
    telefono character varying(10),
    username character varying(30) NOT NULL,
    password text NOT NULL,
    estatus boolean NOT NULL,
    id_rol smallint NOT NULL,
    id_tipo_usuario smallint NOT NULL,
    id_programa_educativo smallint NOT NULL,
    tiempo_creacion timestamp(6) without time zone,
    tempo_actualizacion timestamp(6) without time zone
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- Name: usuario_id_usuario_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario ALTER COLUMN id_usuario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_usuario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: programa_educativo; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.programa_educativo VALUES (1, 'Lic. en Ingeniería de Software', true);
INSERT INTO public.programa_educativo VALUES (2, 'Lic. en Ingeniería de Ciberseguridade Infraestructura de Cómputo', true);
INSERT INTO public.programa_educativo VALUES (3, 'Lic. en Ingeniería en Sistemas y Tecnologías de la Información', true);
INSERT INTO public.programa_educativo VALUES (4, 'Lic. en Ingeniería en Ciencia de Datos', true);
INSERT INTO public.programa_educativo VALUES (5, 'Maestría en Sistemas Interactivos Centrados en el Usuario', true);
INSERT INTO public.programa_educativo VALUES (6, 'Doctorado en Ciencias de la Computación (DCC)', true);
INSERT INTO public.programa_educativo VALUES (7, 'Especialización en Métodos Estadísticos', true);


--
-- Data for Name: rol; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.rol VALUES (1, 'administrador', true);
INSERT INTO public.rol VALUES (2, 'invitado', true);


--
-- Data for Name: tipo_usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.tipo_usuario VALUES (1, 'Docente', true);
INSERT INTO public.tipo_usuario VALUES (2, 'Administrativo', true);
INSERT INTO public.tipo_usuario VALUES (3, 'Alumno', true);


--
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.usuario VALUES (2, 'Super', 'Administrador', '', 'SA-001', 'superadmin@sicae.com', NULL, 'superadmin', '$2a$10$rQFsAd8mb157WOlTQIYzQOEgRKrJKO3EfLXRCkbMnH6UM50smIDn6', true, 1, 1, 1, '2026-06-16 01:13:31.164909', NULL);
INSERT INTO public.usuario VALUES (3, 'Guillermo', 'Gongora', 'Mendoza', 'GGM-761', 'ggmendoza05@hotmail.com', NULL, 'ggm', '$2a$10$rxbXYVi4dOgC3xIvdfBqxuws1vwStEj.KomDWvyxfMtUqHDty.z0C', true, 1, 1, 1, '2026-06-16 17:06:05.822319', NULL);
INSERT INTO public.usuario VALUES (4, 'Guillermo', 'Gongora', 'Mendoza', 'GGM-841', 'ggmendoza2005@gmail.com', NULL, 'prueba1', '$2a$10$6BDBN56hMcqwtA32SZYUdO36IBwQrgz.IzU2s76xUtC1GxUWAD2Xy', true, 1, 1, 1, '2026-06-16 17:06:30.058437', NULL);
INSERT INTO public.usuario VALUES (5, 'Guillermo', 'Gongora', 'Mendoza', 'GGM-846', 'ggmendozaalgo@gmail.com', NULL, 'prueba3', '$2a$10$UmA11GMHzsZ8jyDREtmZE.jBhF8azW2qk98r6PlmAlql/kFwKjZiC', true, 2, 2, 2, '2026-06-16 17:07:14.962526', NULL);
INSERT INTO public.usuario VALUES (6, 'Guillermo', 'Gongora', 'Mendoza', 'GGM-849', 'ggmendozaalgo2@gmail.com', NULL, 'prueba4', '$2a$10$IFE.yyB41YykjaAL2IGm4.hhvwXOTV.egT/OdGvHBIRSPOf2Auheu', true, 1, 1, 1, '2026-06-16 17:17:12.857337', NULL);
INSERT INTO public.usuario VALUES (1, 'Administrador', 'SICAE', NULL, 'ADMIN01', 'admin@sicae.edu.mx', NULL, 'admin', '$2a$10$rQFsAd8mb157WOlTQIYzQOEgRKrJKO3EfLXRCkbMnH6UM50smIDn6', true, 1, 2, 1, '2026-06-16 01:12:48.034235', NULL);
INSERT INTO public.usuario VALUES (7, 'TestAdmin', 'Test', 'Test', 'TTT-457', 'testadmin@test.com', NULL, 'testadmin', '$2a$10$vAQ0xHn8uUw1CMMsZJRwbuQrnrlfR4cCsXJ0zaoHZh5O17KetM3qu', true, 1, 1, 1, '2026-06-16 17:19:32.71931', NULL);
INSERT INTO public.usuario VALUES (8, 'TestUser', 'Test', 'Test', 'TTT-603', 'testuser@test.com', NULL, 'testuser', '$2a$10$NZzG1pJS4v.9WxvgpkPW7.Vs7GisUj3lIj654XqrXtjEcMeqSsBXa', true, 2, 1, 1, '2026-06-16 17:19:32.848174', NULL);
INSERT INTO public.usuario VALUES (9, 'TestUserSec', 'Test', 'Test', 'TTT-218', 'testusersec@test.com', NULL, 'testusersec', '$2a$10$LkeuZmZiSxovkKHG0Qphmu3ZleJ1DclEcHMPElDRVq6bNTUD3OCVS', true, 2, 1, 1, '2026-06-16 17:22:11.135319', NULL);
INSERT INTO public.usuario VALUES (10, 'Guillermo', 'Gongora', 'Mendoza', 'GGM-466', 'prueba5@gmail.com', NULL, 'prueba5', '$2a$10$24RE2G9hUMqOIwDOmyhXh.tt9/O1nBL7rEjgxvojjCrTC37Ws5qBm', true, 2, 2, 4, '2026-06-16 20:11:18.924697', NULL);
INSERT INTO public.usuario VALUES (14, 'Guillermo', 'Gongora', 'Mendoza', 'GGM-125', 'prueba9@gmail.com', NULL, 'prueba9', '$2a$10$ckxnBNT7zlH.1gZPvXoTMevns3tK2u8C5vm.CHXBMKGcFxmB0Afhy', true, 2, 2, 6, '2026-06-16 20:35:12.638552', NULL);
INSERT INTO public.usuario VALUES (15, 'ConTelefono', 'Test', NULL, 'CT-808', 'testtel@test.com', NULL, 'testtel', '$2a$10$pGRnmgpnaZF1mKsEPxzPJuy8CddFygAA6FctUxJc7Gz5PSxCY2ZVy', true, 2, 1, 1, '2026-06-16 20:39:04.347199', NULL);
INSERT INTO public.usuario VALUES (16, 'PruebaTelefono', 'Test', NULL, 'PT-159', 'pruebatel@test.com', NULL, 'pruebatel', '$2a$10$B7.O9k7erxg/mMn4.JFV6.qKwapDKBWTyX6ebgF0jtqCiQGYUGV46', true, 2, 1, 1, '2026-06-16 20:40:55.864753', NULL);
INSERT INTO public.usuario VALUES (17, 'ConTelefonoCuatro', 'Test', NULL, 'CT-501', 'testtel4@test.com', NULL, 'testtel4', '$2a$10$eJ/VJQZksIsHJ/OyKH.Q/euLS90dceqFmgPm9HGE7/WCQhGfHu0v6', true, 2, 1, 1, '2026-06-16 20:41:50.317532', NULL);
INSERT INTO public.usuario VALUES (18, 'ConTelefonoCinco', 'Test', NULL, 'CT-488', 'testtel5@test.com', '1234567890', 'testtel5', '$2a$10$23VWZMoBftFG3eK5I4U2k.JJ2m4SH9nciiuuBprZTL3XL3xTkeyg.', true, 2, 1, 1, '2026-06-16 20:42:59.910301', NULL);
INSERT INTO public.usuario VALUES (19, 'Guillermo', 'Gongora', 'Mendoza', 'GGM-103', 'prueba10@gmail.com', '2223123123', 'prueba10', '$2a$10$4cdukU/yiowCuhThrfQkfuYvWiP85FmEAS0ExjuDae8vvatE5PkJG', true, 2, 2, 6, '2026-06-16 20:46:06.544284', NULL);
INSERT INTO public.usuario VALUES (20, 'Guillermo', 'Gongora', 'Mendoza', 'GGM-321', 'prueba20@gmail.com', '2223123123', 'prueba20', '$2a$10$uWclZBeKJm/oi/QparFqPOq.cFASFXOtK0V7ZGEvv5g86yE5fr8I2', true, 2, 2, 6, '2026-06-17 18:52:40.79387', NULL);
INSERT INTO public.usuario VALUES (21, 'Guillermo', 'Gongora', 'Mendoza', 'GGM-464', 'prueba21@gmail.com', '2223123123', 'prueba21', '$2a$10$vMxQZ03elbluLjQQNMfnvuz3kjdYKgdCofukvC1cN3z.P/4H6oxrm', true, 2, 2, 6, '2026-06-18 00:48:05.234687', NULL);
INSERT INTO public.usuario VALUES (13, 'Guillermo', 'Gongora', 'Mendoza', 'GGM-689', 'prueba8@gmail.com', NULL, 'prueba8', '$2a$10$qLJI4ZH7V9gJwYIkFWB8He4S5cMh0IFuyRpOxGLpZ7TweJgP.Nml.', false, 2, 2, 6, '2026-06-16 20:34:04.530725', NULL);
INSERT INTO public.usuario VALUES (22, 'Guillermo', 'Gongora', 'Mendoza', 'GGM-161', 'prueba24@gmail.com', '2223123123', 'prueba24', '$2a$10$NR2..9gzfvg.3Wlx64GOs.KHPvPoSQKegeilGwqXtcFQi4AdnXZrC', true, 2, 2, 6, '2026-06-18 06:26:08.632355', NULL);
INSERT INTO public.usuario VALUES (23, 'Super', 'Test', 'One', 'STO-424', 'supertest@sicae.com', '1234567890', 'supertest', '$2a$10$LruKCRpqoInkp831rN3H6.nsE01SPgtxSr.B7bwRav8F7gdyrSoAy', true, 2, 2, 1, '2026-06-18 14:39:03.909678', NULL);
INSERT INTO public.usuario VALUES (12, 'Guillermo', 'Gongoration2', 'Mendoza', 'GGM-945', 'prueba7@gmail.com', '2200220022', 'prueba7', '$2a$10$CefT/DLgGLinIVBT3hPawu.HCAG5kM9.bQ2nJ6KmlJanme1968vD.', true, 2, 2, 6, '2026-06-16 20:14:07.469021', '2026-06-18 01:00:00.255376');


--
-- Name: programa_educativo_id_programa_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.programa_educativo_id_programa_seq', 1, false);


--
-- Name: rol_id_rol_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.rol_id_rol_seq', 1, false);


--
-- Name: tipo_usuario_id_tipo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tipo_usuario_id_tipo_seq', 1, false);


--
-- Name: usuario_id_usuario_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuario_id_usuario_seq', 23, true);


--
-- Name: programa_educativo programa_educativo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.programa_educativo
    ADD CONSTRAINT programa_educativo_pkey PRIMARY KEY (id_programa);


--
-- Name: rol rol_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rol
    ADD CONSTRAINT rol_pkey PRIMARY KEY (id_rol);


--
-- Name: tipo_usuario tipo_usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipo_usuario
    ADD CONSTRAINT tipo_usuario_pkey PRIMARY KEY (id_tipo);


--
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario);


--
-- Name: usuario usuario_id_programa_educativo_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_id_programa_educativo_fkey FOREIGN KEY (id_programa_educativo) REFERENCES public.programa_educativo(id_programa);


--
-- Name: usuario usuario_id_rol_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_id_rol_fkey FOREIGN KEY (id_rol) REFERENCES public.rol(id_rol);


--
-- Name: usuario usuario_id_tipo_usuario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_id_tipo_usuario_fkey FOREIGN KEY (id_tipo_usuario) REFERENCES public.tipo_usuario(id_tipo);


--
-- PostgreSQL database dump complete
--

\unrestrict qcGGIkFOhKOT8CaaraSLecakt8ifHnzUyxhhgoRts8h9rlENTEJkRyxFMtZBepb

