/*
 Navicat Premium Dump SQL - Adaptado a snake_case para compatibilidad con Hibernate

 Source Catalog: sicaeUsuario
 Source Schema  : public
*/

-- ----------------------------
-- Table structure for programa_educativo
-- ----------------------------
DROP TABLE IF EXISTS "public"."programa_educativo";
CREATE TABLE "public"."programa_educativo" (
  id_programa int2 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 32767
START 1
CACHE 1
),
  nombre varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  estatus boolean NOT NULL
)
;

-- ----------------------------
-- Records of programa_educativo
-- ----------------------------
INSERT INTO "public"."programa_educativo" VALUES (1, 'Lic. en Ingeniería de Software', true);
INSERT INTO "public"."programa_educativo" VALUES (2, 'Lic. en Ingeniería de Ciberseguridade Infraestructura de Cómputo', true);
INSERT INTO "public"."programa_educativo" VALUES (3, 'Lic. en Ingeniería en Sistemas y Tecnologías de la Información', true);
INSERT INTO "public"."programa_educativo" VALUES (4, 'Lic. en Ingeniería en Ciencia de Datos', true);
INSERT INTO "public"."programa_educativo" VALUES (5, 'Maestría en Sistemas Interactivos Centrados en el Usuario', true);
INSERT INTO "public"."programa_educativo" VALUES (6, 'Doctorado en Ciencias de la Computación (DCC)', true);
INSERT INTO "public"."programa_educativo" VALUES (7, 'Especialización en Métodos Estadísticos', true);

-- ----------------------------
-- Table structure for rol
-- ----------------------------
DROP TABLE IF EXISTS "public"."rol";
CREATE TABLE "public"."rol" (
  id_rol int2 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 32767
START 1
CACHE 1
),
  nombre varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  estatus boolean NOT NULL
)
;

-- ----------------------------
-- Records of rol
-- ----------------------------
INSERT INTO "public"."rol" VALUES (1, 'administrador', true);
INSERT INTO "public"."rol" VALUES (2, 'invitado', true);

-- ----------------------------
-- Table structure for tipo_usuario
-- ----------------------------
DROP TABLE IF EXISTS "public"."tipo_usuario";
CREATE TABLE "public"."tipo_usuario" (
  id_tipo int2 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 32767
START 1
CACHE 1
),
  nombre varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  estatus boolean NOT NULL
)
;

-- ----------------------------
-- Records of tipo_usuario
-- ----------------------------
INSERT INTO "public"."tipo_usuario" VALUES (1, 'Docente', true);
INSERT INTO "public"."tipo_usuario" VALUES (2, 'Administrativo', true);
INSERT INTO "public"."tipo_usuario" VALUES (3, 'Alumno', true);

-- ----------------------------
-- Table structure for usuario
-- ----------------------------
DROP TABLE IF EXISTS "public"."usuario";
CREATE TABLE "public"."usuario" (
  id_usuario int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  nombre varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  apellido_paterno varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  apellido_materno varchar(50) COLLATE "pg_catalog"."default",
  clave_usuario varchar(10) COLLATE "pg_catalog"."default" NOT NULL,
  email varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  telefono varchar(10) COLLATE "pg_catalog"."default",
  username varchar(30) COLLATE "pg_catalog"."default" NOT NULL,
  password text COLLATE "pg_catalog"."default" NOT NULL,
  estatus boolean NOT NULL,
  id_rol int2 NOT NULL,
  id_tipo_usuario int2 NOT NULL,
  id_programa_educativo int2 NOT NULL,
  tiempo_creacion timestamp(6),
  tempo_actualizacion timestamp(6)
)
;

-- ----------------------------
-- Records of usuario (admin seed)
-- admin password: Admin2024!
-- ----------------------------
INSERT INTO "public"."usuario" VALUES (1, 'Administrador', 'SICAE', NULL, 'ADMIN01', 'admin@sicae.edu.mx', NULL, 'admin', '$2a$10$kOs/guKI1ozK1YV3wcfZIe3gbQe3kdHnLazKo1sA4zAdDxHBlEZXS', true, 1, 2, 1, NOW(), NULL);

-- ----------------------------
-- Primary Key structure
-- ----------------------------
ALTER TABLE "public"."programa_educativo" ADD CONSTRAINT "programa_educativo_pkey" PRIMARY KEY (id_programa);
ALTER TABLE "public"."rol" ADD CONSTRAINT "rol_pkey" PRIMARY KEY (id_rol);
ALTER TABLE "public"."tipo_usuario" ADD CONSTRAINT "tipo_usuario_pkey" PRIMARY KEY (id_tipo);
ALTER TABLE "public"."usuario" ADD CONSTRAINT "usuario_pkey" PRIMARY KEY (id_usuario);

-- ----------------------------
-- Foreign Keys structure for table usuario
-- ----------------------------
ALTER TABLE "public"."usuario" ADD CONSTRAINT "usuario_id_programa_educativo_fkey" FOREIGN KEY (id_programa_educativo) REFERENCES "public"."programa_educativo" (id_programa) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."usuario" ADD CONSTRAINT "usuario_id_rol_fkey" FOREIGN KEY (id_rol) REFERENCES "public"."rol" (id_rol) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."usuario" ADD CONSTRAINT "usuario_id_tipo_usuario_fkey" FOREIGN KEY (id_tipo_usuario) REFERENCES "public"."tipo_usuario" (id_tipo) ON DELETE NO ACTION ON UPDATE NO ACTION;
