spring.application.name=users
server.port=8083

# Configuración para PostgreSQL
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/sicaeUsuario
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# JWT Configuration
app.jwtSecret=c3VwZXJzZWNyZXRrZXlmb3JzaWNhZXByb2plY3R0aXMyMDI2d2l0aGF0bGVhc3QyNTZiaXRzb2ZsZW5ndGg=
app.jwtExpirationMs=86400000
